version: "3"
services:
  etcd1:
    image: quay.io/coreos/etcd
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "12379:2379"
      - "12380:2380"
    volumes:
      - data1:/etcd-data
    networks:
      - net
    command: /usr/local/bin/etcd --data-dir /etcd-data --name node1 --initial-advertise-peer-urls http://etcd1:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://etcd1:2379 --listen-client-urls http://0.0.0.0:2379 -discovery http://IP/TOKEN
  etcd2:
    image: quay.io/coreos/etcd
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "22379:2379"
      - "22380:2380"
    volumes:
      - data2:/etcd-data
    networks:
      - net
    command: /usr/local/bin/etcd --data-dir /etcd-data --name node2 --initial-advertise-peer-urls http://etcd2:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://etcd2:2379 --listen-client-urls http://0.0.0.0:2379 -discovery http://IP/TOKEN
  etcd3:
    image: quay.io/coreos/etcd
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "32379:2379"
      - "32380:2380"
    volumes:
      - data3:/etcd-data
    networks:
      - net
    command: /usr/local/bin/etcd --data-dir /etcd-data --name node3 --initial-advertise-peer-urls http://etcd3:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://etcd3:2379 --listen-client-urls http://0.0.0.0:2379 -discovery http://IP/TOKEN
    
networks:
  net:

volumes:
  data1:
  data2:
  data3:
  
